Making a start on updating the iOS documentation
netsells/code-standards pull request #403
Opened 2021-07-27 10:18 UTC by jackcolley

Bringing iOS documentation up to date and providing a foundation to build on

2021-07-28 06:56 UTC, ptrbrynt requested changes
Really good stuff here! Just a few typos and spelling things but overall looking great 👍🏻

2021-07-28 06:56 UTC, ptrbrynt commented on src/flutter/codesigning.md
> +For the iOS part of flutter apps, we use [Fastlane Match](https://docs.fastlane.tools/actions/match/) to manage signing certificates and provisioning profiles.
Typo
```suggestion
For the iOS part of Flutter apps, we use [Fastlane Match](https://docs.fastlane.tools/actions/match/) to manage signing certificates and provisioning profiles.
```

2021-07-28 06:56 UTC, ptrbrynt commented on src/flutter/codesigning.md
> +This means that should the project ever need to be transferred or outsource engineers added to the repo, we don't have to expose all other projects certificates and profiles.
This is a good idea - I'll update the Flutter template's `Matchfile`.

2021-07-28 06:56 UTC, ptrbrynt commented on src/ios/README.md
> +This is a living document that aims to document the agreed set of code standards for the iOS team. Please discuss any changes with the wider team before updating this document
```suggestion
This is a living document that aims to document the agreed set of code standards for the iOS team. Please discuss any changes with the wider team before updating this document.
```

2021-07-28 06:56 UTC, ptrbrynt commented on src/ios/README.md
> +Opening a PR - Opening a PR will trigger a build that runs the automated tests and code quality tools then reports back to Github
```suggestion
Opening a PR - Opening a PR will trigger a build that runs the automated tests and code quality tools then reports back to GitHub
```

2021-07-28 06:56 UTC, ptrbrynt commented on src/ios/README.md
> +Once the branches are set, Github will populate the description with a pull request template. You should fill this template in with as much detail as possible for the reviewer.
```suggestion
Once the branches are set, GitHub will populate the description with a pull request template. You should fill this template in with as much detail as possible for the reviewer. 
```

2021-07-28 06:56 UTC, ptrbrynt commented on src/ios/architecture.md
> +* It is a good idea (not a requirement) to use a Codable model as a DTO (Data Transfer Object) which represents the structure of the data returned from external services. These can then be converted
```suggestion
* It is a good idea (not a requirement) to use a Codable model as a DTO (Data Transfer Object) which represents the structure of the data returned from external services. These can then be converted to and from your entity struct. This means that your entities are not dependent on the data structure of the objects returned from external sources.
```

2021-07-28 06:56 UTC, ptrbrynt commented on src/ios/architecture.md
> +* A view’s state (@State) should only be used when absolutely necessary (e.g when building a form). Most of the time, it is far better to use the view model to hold and control all state.
```suggestion
* A view’s state (`@State`) should only be used when absolutely necessary (e.g when building a form). Most of the time, it is far better to use the view model to hold and control all state.
```

2021-07-28 06:56 UTC, ptrbrynt commented on src/ios/bundler.md
> +If you want to use cocoapods or fastlane, you simply need to prefix their commands with bundle exec
```suggestion
If you want to use Cocoapods or Fastlane, you simply need to prefix their commands with `bundle exec`
```

2021-07-28 06:56 UTC, ptrbrynt commented on src/ios/testing.md
> +Comprehensive automated tests are a crucial component of a healthy codebase. Not only do they allow behavious to be continuously verified as changes are made to a project. They also encourage good de
```suggestion
Comprehensive automated tests are a crucial component of a healthy codebase. Not only do they allow behaviours to be continuously verified as changes are made to a project; they also encourage good development habits, boost productivity and serve as living documentation for the intended functionality of your code.
```

2021-07-28 06:56 UTC, ptrbrynt commented on src/ios/testing.md
> +We spend a lot of time in refinement sessions breaking down each ticket and writing the acceptance critieria for all functionality. Try to write your tests to match and verifiy the acceptance critera
```suggestion
We spend a lot of time in refinement sessions breaking down each ticket and writing the acceptance critieria for all functionality. Try to write your tests to match and verify the acceptance critera for the ticket you are working on. 
```

2021-07-28 06:56 UTC, ptrbrynt commented on src/ios/testing.md
> +Its ok to be firm on this principle when communicating with non-technical staff. Ticket estimates should and must include sufficient allowance for engineers to write high-quality, well-tested code.
```suggestion
Its okay to be firm on this principle when communicating with non-technical staff. Ticket estimates should and must include sufficient allowance for engineers to write high-quality, well-tested code.
```

2021-07-28 06:56 UTC, ptrbrynt commented on src/ios/testing.md
> +Skipping tests today might save you time, but you are exchanging the saved time for technical debt. An untested codebase can’t scale efficiently, and will beocme more and more difficult to work on ov
```suggestion
Skipping tests today might save you time, but you are exchanging the saved time for technical debt. An untested codebase can’t scale efficiently, and will become more and more difficult to work on over time. The time you might save by not writing a test will need to be paid back - with significant interest later down the line.
```

2021-08-04 12:23 UTC, jackcolley commented
Thanks for the feedback @ptrbrynt - I've updated

2021-08-10 07:07 UTC, ptrbrynt approved these changes

2021-08-10 07:07 UTC, merged